### PR TITLE
LPD-39232 [forms] Review PR "Allow using directive script-src-attr 'none' by removing inline handlers"

### PR DESCRIPTION
**Pull request by izaera**
This is a rework of https://github.com/liferay-forms/liferay-portal/pull/2643 using a newer approach that has already been merged to master.

In theory the code is equivalent to the original one, but it would probably be wise checking everything at CI again just in case...

### CODE REVIEW

**Comment by izaera** [comment]
ci:test:sf

**Comment by carolmariaabb** [comment]
ci:test:forms

**Comment by igor-franca** [comment]
ci:stop

**Comment by igor-franca** [comment]
ci:test:sf

**Comment by igor-franca** [comment]
ci:test:forms

**Comment by igor-franca** [comment]
ci:report:57115088

**Comment by igor-franca** [comment]
ci:report:57115088

**Comment by igor-franca** [comment]
Crashes reported as single faults passed locally in the PR branch:

> ImageField#UploadImageFromDocumentsAndMedia
> FormsTextField#CanBeAutocompletedUsingADataProvider
> LocalizedSimpleFieldsWebContent#TranslateWebContentWithAllFields

Test Localizable#EditLocalizableOnPublishedWCWithFieldset failed both on the PR branch and locally on master

**Comment by igor-franca** [comment]
ci:forward

**Pull request closed without merging**
