### PR TITLE
LPD-43553 Insert hyphen when using the language key

### PR DESCRIPTION
**Pull request by igor-franca**
related [ticket](https://liferay.atlassian.net/browse/LPD-43553)

### CODE REVIEW

**Comment by igor-franca** [comment]
Hey @victorKammerer, could you check the other uses of keys and find out if they agree?

**Comment by igor-franca** [comment]
ci:test:sf

**Review by gabrielwas — APPROVED** [review]
LGTM! Thx @igor-franca !

**Comment by gabrielwas** [comment]
ci:forward

**Comment by marcelabc** [comment]
ci:test:relevant

**Comment by marcelabc** [comment]
ci:test:sf

**Comment by marcelabc** [comment]
Hey @igor-franca 
Even though the stable has failed (a known issue), you can check the results using the Testray link.

**Comment by igor-franca** [comment]
Comparing all other language keys changed in the story and not identifying any other difference between key and usage, I am sending the PR forward manually.

Sorry for the delay, crazy day here

**Comment by igor-franca** [comment]
resent [here](https://github.com/brianchandotcom/liferay-portal/pull/156705)

**Pull request closed without merging**
