### PR TITLE
LPD-40974 

### PR DESCRIPTION
**Pull request by thiago-buarqque**
Sending here as part of the collaboration between BPM and Platform Experience regarding backend SF/patterns reviews.

--

https://liferay.atlassian.net/browse/LPD-40974
https://liferay.atlassian.net/browse/LPD-43078

There was a bug in the fix I sent here https://github.com/liferay-platform-experience/liferay-portal/pull/781

I was using the outdated preferences to update the database. `_featureFlagsBagProvider.setEnabled` updates the flags portal preferences, but the reference got in the beginning of the method is outdated. Getting the updated preferences after setting the flags to false.

### CODE REVIEW

**Comment by thiago-buarqque** [comment]
CI ran on https://github.com/liferay-platform-experience/liferay-portal/pull/826

**Review by linolaoj — APPROVED** [review]

**Comment by thiago-buarqque** [comment]
ci:test:sf

**Comment by thiago-buarqque** [comment]
ci:test:relevant

**Comment by thiago-buarqque** [comment]
ci:test:relevant

**Comment by thiago-buarqque** [comment]
ci:test:relevant

**Comment by thiago-buarqque** [comment]
ci:test:relevant

**Comment by thiago-buarqque** [comment]
ci:report:82835398

**Comment by thiago-buarqque** [comment]
ci:test:relevant

**Comment by thiago-buarqque** [comment]
[CI is having issues lately](https://liferay.slack.com/archives/C19PWQ74J/p1733224766797639). Since CI passed in https://github.com/liferay-platform-experience/liferay-portal/pull/826 I will forward it directly to Brian.

**Comment by thiago-buarqque** [comment]
Sent to https://github.com/brianchandotcom/liferay-portal/pull/156665

**Pull request closed without merging**
