### PR TITLE
LPD-42915 - The "Get definition page" endpoint fails when a related object uses the Status system field as entry title

### PR DESCRIPTION
**Pull request by JhossephG**
We are ensuring that meta fields that have some specificities are receiving the right data type.

### CODE REVIEW

**Comment by JhossephG** [comment]
ci:test:relevant

**Comment by linolaoj** [comment]
As we talked, @JhossephG is going to add a unit test, and check why the `status` field is with `dbType` `text` instead of `integer`.

**Comment by JhossephG** [comment]
ci:stop

**Comment by JhossephG** [comment]
ci:test:sf

**Comment by JhossephG** [comment]
ci:stop

**Comment by JhossephG** [comment]
ci:test:relevant

**Comment by JhossephG** [comment]
ci:test:relevant

**Comment by JhossephG** [comment]
ci:test:relevant

**Comment by JhossephG** [comment]
ci:stop

**Comment by JhossephG** [comment]
ci:test:relevant

**Comment by JhossephG** [comment]
ci:test:sf

**Comment by JhossephG** [comment]
ci:test:relevant

**Comment by JhossephG** [comment]
ci:test:relevant

**Comment by JhossephG** [comment]
ci:test:relevant

**Comment by JhossephG** [comment]
ci:test:sf

**Comment by JhossephG** [comment]
ci:forward:force

**Pull request closed without merging**
