### PR TITLE
LPD-41969 Missing CDATA content for empty web content fields

### PR DESCRIPTION
**Pull request by marcelabc**
Related issue: https://liferay.atlassian.net/browse/LPD-41969

### CODE REVIEW

**Comment by marcelabc** [comment]
ci:test:sf

**Comment by marcelabc** [comment]
hey @icgsbr 
Can you double-check this solution locally and check the CI results, please?

**Comment by marcelabc** [comment]
If everything works as expected, you can forward this solution :+1:

**Comment by marcelabc** [comment]
ci:test:relevant

**Comment by marcelabc** [comment]
ci:test:data-engine

**Comment by icgsbr** [comment]
ci:forward

**Pull request closed without merging**
