### PR TITLE
LPD-41062 Limit columns width to avoid unnecessary oversizing of permission inheritance column

### PR DESCRIPTION
**Pull request by larissacribeiro**
This is a follow up to: https://github.com/liferay-bpm/liferay-portal/pull/3823
Since now we are not going to wait on clay's table FF, we need to manipulate the table width on our side a little bit to match the expected result on our mockups. This should be just an temporary patch until their FF is released. 

Ideally, we would manipulate only permission inheritance column's width, but I haven't been able to do it the way they [suggested](https://liferay.atlassian.net/browse/PTR-5744) , the mentioned example is [here](https://github.com/liferay-bpm/liferay-portal/blob/f5622597a246a420a973db4f0631fa74877b3aba/modules/apps/commerce/commerce-theme-minium/commerce-theme-minium/src/css/minium/overrides/_data-set-display.scss#L92), customizing an commerce table, so it should be something like this for our case: 
```
.dnd-table {
		.dnd-td,
		.dnd-th {
			&.cell-permissionInheritance {
				max-width: 150px;
			}
		}
	}
```

But that code was never applied to the cell even using !important, so instead of manipulating only the cell, I've limited the whole card to the maximum width that will keep the column's title in two lines instead of one. Please let me know your thoughts on this, thanks!

### CODE REVIEW

**Comment by larissacribeiro** [comment]
ci:test:sf

**Comment by rebsilva** [comment]
hi @larissacribeiro! i will take a look at this later today, thanks!

**Review by rebsilva — CHANGES_REQUESTED** [review]
hi @larissacribeiro! thanks for this PR :blush:

after testing the code i realized that these css changes don't correspond to every screen resolution, so it could be a problem. 

instead, i've tried to use the suggestion given by the front-end team and it worked for me; please see the code below that i've applied on the `ViewObjectDefinitions.scss` file:
```
// TODO: remove this css with the LPS-193005 feature flag removal

.dnd-table {
	.dnd-td,
	.dnd-th {
		&.cell-permissionInheritance {
			max-width: 125px;
			background: purple;
		}

		&.cell-label {
			min-width: 250px;
			background: blue
		}
	}
}
```

this way you can define the `min-width` or `max-width` of every cell and it doesn't depend on the user screen resolution. also i've put a `TODO` comment there so we can remember to delete this code after the clay table feature flag is removed.

let me know if you need help with this so we can work together, thanks! :cherry_blossom:

**Comment by rebsilva** [comment]
we discovered that the override function on the devtools was the villain all along, not letting larissa apply her changes :angry: now that this configuration is disabled, she will be able to work on this! :pray: thanks lari! :bear:

**Comment by larissacribeiro** [comment]
thanks so much for your review, @rebsilva!! 💟 I've just pushed the requested changes, can you take another look when possible? Thanks!!

**Comment by larissacribeiro** [comment]
ci:test:sf

**Comment by rebsilva** [comment]
yes, i will take a look now!

**Review by rebsilva — APPROVED** [review]
LGTM! great work on this @larissacribeiro! :tada: :purple_heart:

**Comment by larissacribeiro** [comment]
ci:test:sf

**Comment by larissacribeiro** [comment]
ci:test:object

**Comment by larissacribeiro** [comment]
ci:forward:force

**Pull request closed without merging**
