### PR TITLE
LPD-42818 - Add uuid column to KaleoDefinition entity

### PR DESCRIPTION
**Pull request by JhossephG**
We are adding the uuid column to the KaleoDefinition entity to keep the ERC pattern as requested for product team.

### CODE REVIEW

**Comment by JhossephG** [comment]
ci:test:sf

**Comment by linolaoj** [comment]
Hi @JhossephG, the commit SF (https://github.com/liferay-bpm/liferay-portal/pull/3903/commits/ae05d151fd001b3066f381980a1faf2decacdbfe) is adding a new file. Can you please run it again and replace the commit?

**Comment by JhossephG** [comment]
ci:test:sf

**Comment by JhossephG** [comment]
ci:test:relevant

**Comment by JhossephG** [comment]
ci:test:sf

**Comment by linolaoj** [comment]
As we talked the pr will be rebased using the liferay-bpm/master branch as base.

**Comment by JhossephG** [comment]
resent [here](https://github.com/liferay-bpm/liferay-portal/pull/3903)

**Pull request closed without merging**
