### PR TITLE
LPD-41061 - Follow up

### PR DESCRIPTION
**Pull request by JhossephG**
Follow up from [LPD-41061](https://liferay.atlassian.net/browse/LPD-41061). 

We need to check if the values are null too.

[LPD-41061]: https://liferay.atlassian.net/browse/LPD-41061?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

### CODE REVIEW

**Comment by JhossephG** [comment]
ci:test:sf

**Comment by JhossephG** [comment]
ci:test:relevant

**Comment by JhossephG** [comment]
ci:test:sf

**Comment by JhossephG** [comment]
ci:test:relevant

**Review by linolaoj — APPROVED** [review]

**Comment by JhossephG** [comment]
ci:test:relevant

**Comment by linolaoj** [comment]
ci:forward

**Pull request closed without merging**
