### PR TITLE
LPD-37732 Technical Task | Move tests of object-rest-test to the Headless team

### PR DESCRIPTION
**Pull request by magjed4289**
Hey @liferay-objects!
Sending this PR for your review as we ended up modifying the test.properties of the object module, as well as creating a separate test.properties for the object-rest-test package.

**Why is this needed?**
Currently, the tests from object-rest-* is shown in Testray as owned by [Business Process Management](https://testray.liferay.com/#/project/35392/routines/1846019/build/40099630/case-result/40109343), which is incorrect. To assign the correct owner we have added a separate file and modified it so it's seen as owned by the Headless team. It will help check the test results when we apply the new flow of checking each team's tests in only one run, common for all the teams.

**Before the change:**
image
**After the change:**
image

The number of tests in each team's test suite does not change. I'm executing both suites on this pull to validate the changes one more time.

https://liferay.atlassian.net/browse/LPD-37732
cc @4lejandrito

### CODE REVIEW

**Comment by magjed4289** [comment]
ci:test:object

**Comment by magjed4289** [comment]
ci:test:headless

**Review by guilhermedcamacho — APPROVED** [review]
LGTM :tada:

**Comment by guilhermedcamacho** [comment]
Hey @magjed4289, as you mentioned, please review the CI results of both suites to validate the changes once again. If everything is correct you can forward the PR.

**Comment by magjed4289** [comment]
ci:forward

**Pull request closed without merging**
