### PR TITLE
LPD-41330 Modifications to truncate the nanoseconds into millisecond

### PR DESCRIPTION
**Pull request by yuriymr**
Modifications to truncate the nanoseconds into millisecond avoiding the error on the SalesforceObjectEntryManagerImplTest.testGetObjectEntries test.

### CODE REVIEW

**Comment by yuriymr** [comment]
ci:test:object-db-integration

**Comment by yuriymr** [comment]
ci:test:object-db-integration

**Comment by yuriymr** [comment]
ci:report:93992129

**Comment by yuriymr** [comment]
ci:test:object-db-integration

**Comment by yuriymr** [comment]
ci:report:94506582

**Comment by yuriymr** [comment]
ci:test:relevant

**Comment by yuriymr** [comment]
ci:report:94912127

**Comment by yuriymr** [comment]
ci:report:94912127

**Comment by yuriymr** [comment]
I've finished the analysis of the report [testray-results-94912127.csv](https://test-1-37.liferay.com/userContent/jobs/generate-testray-csv/builds/554/testray-results-94912127.csv), and there is no errors related to the SalesforceObjectEntryManagerImplTest.

**Review by guilhermedcamacho — APPROVED** [review]

**Comment by guilhermedcamacho** [comment]
ci:forward:force

**Comment by guilhermedcamacho** [comment]
I fixed the SF issue and manually forwarded it to [brianchandotcom#157245](https://github.com/brianchandotcom/liferay-portal/pull/157245)

**Pull request closed without merging**
