### PR TITLE
LPD-40087 and LPD-41111 - Technical Task | Create Workflow Definition Links endpoint by ERC/ID and export/import batch

### PR DESCRIPTION
**Pull request by JhossephG**
This is the PR with the needs to implement the features from story [LPD-36879](https://liferay.atlassian.net/browse/LPD-36879).

PR of the first task https://github.com/brianchandotcom/liferay-portal/pull/155702

PR of the second task https://github.com/liferay-bpm/liferay-portal/pull/3780

And it implement the features from story [LPD-36881
](https://liferay.atlassian.net/browse/LPD-36881) as well.

[LPD-36879]: https://liferay.atlassian.net/browse/LPD-36879?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

### CODE REVIEW

**Comment by JhossephG** [comment]
ci:test:sf

**Comment by JhossephG** [comment]
ci:test:sf

**Review by linolaoj — APPROVED** [review]

**Comment by JhossephG** [comment]
ci:test:sf

**Comment by JhossephG** [comment]
ci:test:relevant

**Comment by JhossephG** [comment]
The only unique failure in relevant test suite is alerting that the test detected build Rest changes @linolaoj. Should I forward?

**Comment by JhossephG** [comment]
ci:test:relevant

**Comment by linolaoj** [comment]
ci:test:relevant

**Comment by JhossephG** [comment]
ci:test:relevant

**Pull request closed without merging**
