### PR TITLE
LPD-37785

### PR DESCRIPTION
**Pull request by carolmariaabb**
https://liferay.atlassian.net/browse/LPD-37785

### CODE REVIEW

**Comment by carolmariaabb** [comment]
ci:test:sf

**Review by linolaoj — APPROVED** [review]

**Comment by carolmariaabb** [comment]
ci:test:object

**Comment by carolmariaabb** [comment]
ci:test:relevant

**Comment by carolmariaabb** [comment]
ci:report:56527559

**Comment by carolmariaabb** [comment]
ci:forward

**Pull request closed without merging**
