### PR TITLE
LPD-41332 Remove old usages of previous binding approach

### PR DESCRIPTION
**Pull request by victorKammerer**
Jira ticket: [LPD-41332](https://liferay.atlassian.net/browse/LPD-41332)

reopen from: [liferay-bpm#3819]( https://github.com/liferay-bpm/liferay-portal/pull/3819)

[LPD-41332]: https://liferay.atlassian.net/browse/LPD-41332?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

### CODE REVIEW

**Comment by victorKammerer** [comment]
ci:test:relevant

**Comment by victorKammerer** [comment]
ci:test:object

**Comment by victorKammerer** [comment]
ci:test:relevant

**Review by MarinhoFeliphe — CHANGES_REQUESTED** [review]
@victorKammerer see my comments, your changes looks good to me, I've just pointed two things that are not clear to me.

Thank you!

**Comment by victorKammerer** [comment]
ci:test:sf

**Comment by victorKammerer** [comment]
ci:test:relevant

**Review by MarinhoFeliphe — COMMENTED** [review]
LGTM!! :tada:

**Review by MarinhoFeliphe — APPROVED** [review]
LGTM!! :tada:

**Comment by victorKammerer** [comment]
ci:test:sf

**Comment by victorKammerer** [comment]
ci:test:relevant

**Comment by victorKammerer** [comment]
ci:forward

**Comment by victorKammerer** [comment]
ci:forward

**Comment by victorKammerer** [comment]
ci:relevant

**Comment by victorKammerer** [comment]
ci:test:relevant

**Comment by MarinhoFeliphe** [comment]
ci:forward

**Pull request closed without merging**
