### PR TITLE
LPD-43173

### PR DESCRIPTION
**Pull request by JhossephG**

### CODE REVIEW

**Comment by JhossephG** [comment]
ci:test:sf

**Comment by JhossephG** [comment]
ci:test:sf

**Comment by JhossephG** [comment]
ci:test:relevant

**Comment by JhossephG** [comment]
ci:test:workflow

**Comment by JhossephG** [comment]
ci:report:95954951

**Comment by JhossephG** [comment]
ci:test:sf

**Comment by guilhermedcamacho** [comment]
I removed the [commit](https://github.com/liferay-bpm/liferay-portal/pull/3992/commits/579c277fb3d28231902d10734858978d9538ce8d) and manually forwarded to [brianchandotcom#157226](https://github.com/brianchandotcom/liferay-portal/pull/157226)

**Pull request closed without merging**
