### PR TITLE
LPD-39107 Create and use a modal to confirm the delete action of picklist items

### PR DESCRIPTION
**Pull request by rebsilva**
Related issue: https://liferay.atlassian.net/browse/LPD-39107

### CODE REVIEW

**Comment by rebsilva** [comment]
ci:test:sf

**Comment by rebsilva** [comment]
ci:test:sf

**Review by larissacribeiro — APPROVED** [review]
LGTM!! 💟

**Comment by larissacribeiro** [comment]
ci:test:relevant

**Comment by larissacribeiro** [comment]
ci:test:playwright

**Comment by rebsilva** [comment]
ci:test:playwright

**Comment by rebsilva** [comment]
all the object-web playwright tests didn't run properly, so i'm starting the tests again

**Comment by rebsilva** [comment]
ci:test:object

**Comment by rebsilva** [comment]
test failures not related!

**Comment by rebsilva** [comment]
ci:forward:force

**Pull request closed without merging**
