### PR TITLE
LPD-43403 Perform this query via ES instead of relational database due to the complexity of retrieving the latest process definition versions

### PR DESCRIPTION
**Pull request by MarinhoFeliphe**
Related: https://liferay.atlassian.net/browse/LPD-43403

## Situation

CAST_LONG function cannot be applied for VARCHAR columns that has the content like 1.1 or 1.0 on PostegreSQL, so to avoid situations with many relational databases peculiarities I decided to perform this query on ES due to its complexity.

`SQL Error [22P02]: ERROR: invalid input syntax for type bigint: "1.0"`

## Fix

CAST_LONG function was being used to retrieve the latest version of each process definition ([see](https://github.com/liferay-bpm/liferay-portal/pull/3978/files#diff-5e43287d614ea6b5789af4187f0a5c95f572ac6031d15f401549d9a44b61141dL412-L429)) but as mentioned above, it is not supported by PostgreSQL so to achieve the same result via ES I used a nested aggregation, the [first one](https://github.com/liferay-bpm/liferay-portal/pull/3978/files#diff-5e43287d614ea6b5789af4187f0a5c95f572ac6031d15f401549d9a44b61141dR431-R433) is responsible for aggregating the results by the process definition name that is unique, and the [second aggregation](https://github.com/liferay-bpm/liferay-portal/pull/3978/files#diff-5e43287d614ea6b5789af4187f0a5c95f572ac6031d15f401549d9a44b61141dR435-R444) that is the nested to the first one is responsible for sort descending all process definition versions by their version and then get only the first result.

## Test

[See](https://github.com/liferay/liferay-portal/blob/8db0beb67420773df8a6cc812fdbd5119110e4ce/modules/apps/portal-workflow/portal-workflow-kaleo-test/src/testIntegration/java/com/liferay/portal/workflow/kaleo/service/test/KaleoDefinitionVersionLocalServiceTest.java#L64), in my perspective we do not need a test covering this specific use case with PostgreSQL, the already existing test cover the functionality.

### CODE REVIEW

**Comment by MarinhoFeliphe** [comment]
ci:test:sf

**Comment by MarinhoFeliphe** [comment]
ci:test:relevant

**Comment by MarinhoFeliphe** [comment]
ci:test:workflow

**Comment by MarinhoFeliphe** [comment]
ci:test:workflow

**Review by guilhermedcamacho — APPROVED** [review]

**Comment by guilhermedcamacho** [comment]
Since you mentioned that you have already reviewed the CI results, I'm forwarding this PR to Brian.

**Comment by guilhermedcamacho** [comment]
ci:forward:force

**Pull request closed without merging**
