### PR TITLE
LPD-38883 Avoid sending duplicated values when submitting the form

### PR DESCRIPTION
**Pull request by rebsilva**
related issue: https://liferay.atlassian.net/browse/LPD-38883

the following tests already covers this case:
- Forms#SubmitFormWithMultipleFieldsAndViewEntriesViaDescriptiveDisplay
- FormsSubmissions#CanBeSubmittedWithARequiredField

hi reviewer! :cherry_blossom: 

here is a brief explanation about this bug (that is also on the commit message):

_before we had a condition to return null instead of a hidden input when the locale was the same as the editingLanguageId, avoiding the value to be submitted twice._

_this condition was necessary because the current inputs the user is editing already have the values on the screen (and also on the DOM), thus there isn't a need for hidden values for the current editingLanguageId. when this condition was removed, values started to be sent twice._

_since the web content translation manager now needs all the hidden inputs to calculate their translations, the condition was changed to not add the name attribute into the input hidden that has the same locale as the current editingLanguageId; this way, the value from the input hidden won't be submitted and the value will be sent only once._

if you have any questions please let me know, thanks!

cc: @cgmonte

### CODE REVIEW

**Comment by rebsilva** [comment]
ci:test:sf

**Comment by rebsilva** [comment]
ci:test:relevant

**Comment by rebsilva** [comment]
ci:test:playwright

**Comment by igor-franca** [comment]
Just starting the review 😄

**Comment by rebsilva** [comment]
ci:reevaluate:1267401_13993

**Comment by rebsilva** [comment]
test failures are not related, waiting for the reevaluate result for the relevant suite

**Comment by rebsilva** [comment]
the failures are not related! can i forward this @igor-franca?

**Comment by igor-franca** [comment]
Hey @rebsilva , I had the opportunity to create a branch yesterday to study this problem. Although it is a small solution, it involves other details. I should add my considerations here soon.

**Comment by rebsilva** [comment]
@igor-franca right, thanks for the review! you can come and talk to me and carlos about the reason behind this solution and discuss if there is a better approach; but let's do this as soon as possible because this is a release blocker; thanks!

**Comment by rebsilva** [comment]
ci:test:relevant

**Review by igor-franca — APPROVED** [review]
We had the opportunity to talk in person and agreed to send this with some caveats related to the root cause of this issue that will be addressed in the future!

Great job finding this fix Rebecca! 😄

**Comment by rebsilva** [comment]
sent directly to brian: https://github.com/brianchandotcom/liferay-portal/pull/155296

**Pull request closed without merging**
