### PR TITLE
LPD-43173

### PR DESCRIPTION
**Pull request by JhossephG**
[LPD-43173](https://liferay.atlassian.net/browse/LPD-43173)

Adding ERC to WorkflowDefinitionLink.
Creating putWorkflowDefinitionLinkByERC endpoint.
Preventing to allow add duplicated links in the same group.
Refactors

[LPD-43173]: https://liferay.atlassian.net/browse/LPD-43173?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

### CODE REVIEW

**Comment by JhossephG** [comment]
ci:test:relevant

**Comment by JhossephG** [comment]
ci:test:sf

**Comment by JhossephG** [comment]
ci:test:sf

**Comment by JhossephG** [comment]
ci:test:relevant

**Comment by JhossephG** [comment]
ci:test:relevant

**Review by linolaoj — APPROVED** [review]

**Comment by JhossephG** [comment]
ci:stop

**Comment by JhossephG** [comment]
ci:test:relevant

**Comment by JhossephG** [comment]
ci:stop

**Comment by JhossephG** [comment]
ci:test:relevant

**Comment by JhossephG** [comment]
ci:test:relevant

**Comment by JhossephG** [comment]
ci:test:sf

**Comment by JhossephG** [comment]
ci:test:relevant

**Comment by JhossephG** [comment]
ci:forward:force

**Comment by gabrielwas** [comment]
ci:reevaluate:1407401_12257

**Comment by JhossephG** [comment]
resent [here](https://github.com/liferay-bpm/liferay-portal/pull/3966)

**Pull request closed without merging**
