### PR TITLE
LPD-39825 Fix playwright timeout issue

### PR DESCRIPTION
**Pull request by igor-franca**
Related [ticket](https://liferay.atlassian.net/browse/LPD-39825)

I would like to have time to make changes to the other tests in this file.

We can create a fixture to isolate the user, so we don't have to worry about clean up.
Furthermore, we can study other ways to cover the uses of `goto('pt')`. To eliminate its uses in our tests.

### CODE REVIEW

**Comment by igor-franca** [comment]
ci:test:sf

**Comment by igor-franca** [comment]
ci:test:playwright

**Review by rebsilva — APPROVED** [review]
LGTM! :tada: 

just to confirm @igor-franca, at some point we need to return to the code that was reverted right? it would be the case to create a task so we can prioritize inside the team?

**Comment by igor-franca** [comment]
ci:report:48302839

**Comment by igor-franca** [comment]
> LGTM! 🎉
> 
> just to confirm @igor-franca, at some point we need to return to the code that was reverted right? it would be the case to create a task so we can prioritize inside the team?

Hey @rebsilva, there is already a task mapped for this. But the headless team is working to try to correct this error to avoid the revert.

**Comment by igor-franca** [comment]
Pushing forward only the commit related to listTypeDefinition

**Comment by igor-franca** [comment]
ci:forward

**Pull request closed without merging**
