### PR TITLE
LPD-39826

### PR DESCRIPTION
**Pull request by abesousa**
Related issue: [link](https://liferay.atlassian.net/browse/LPD-39826)

### CODE REVIEW

**Comment by abesousa** [comment]
ci:test:sf

**Comment by abesousa** [comment]
ci:test:relevant

**Comment by abesousa** [comment]
Running the Object suite because we are adding a new test file and we need to check if the suite finds and executes it without any configuration.

**Comment by rebsilva** [comment]
ci:test:sf

**Review by rebsilva — APPROVED** [review]
LGTM!

**Comment by rebsilva** [comment]
ci:test:relevant

**Comment by rebsilva** [comment]
ci:test:object

**Comment by cgmonte** [comment]
ci:test:relevant

**Comment by igor-franca** [comment]
The proposed test ran successfully on the relevant:

image

**Comment by cgmonte** [comment]
ci:report:57060948

**Comment by igor-franca** [comment]
To run this test in the object routine, I would bet that adding js-unit to the objects section of the test.properties file could make this happen:

```
    test.batch.names[object]=\
        central-requirements,\
        functional-tomcat90-mysql57,\
        functional-upgrade-tomcat90-mariadb102,\
        functional-upgrade-tomcat90-mysql57,\
        functional-upgrade-tomcat90-postgresql134,\
        functional-upgrade-tomcat90-sqlserver2017,\
        js-unit,\
        modules-integration-mysql57,\
        modules-semantic-versioning,\
        modules-unit,\
        playwright-compile,\
        playwright-js-tomcat90-mysql57,\
        semantic-versioning
```

**Comment by cgmonte** [comment]
> To run this test in the object routine, I would bet that adding js-unit to the objects section of the test.properties file could make this happen:
> 
> ```
>     test.batch.names[object]=\
>         central-requirements,\
>         functional-tomcat90-mysql57,\
>         functional-upgrade-tomcat90-mariadb102,\
>         functional-upgrade-tomcat90-mysql57,\
>         functional-upgrade-tomcat90-postgresql134,\
>         functional-upgrade-tomcat90-sqlserver2017,\
>         js-unit,\
>         modules-integration-mysql57,\
>         modules-semantic-versioning,\
>         modules-unit,\
>         playwright-compile,\
>         playwright-js-tomcat90-mysql57,\
>         semantic-versioning
> ```

Thats is great, Igor, we should talk to Gabriel to consider the addition of unit tests to the object suite. Or not... if you think about it, relevant runs in every PR, so we are safe.

**Comment by cgmonte** [comment]
I I have analysed the results together with @abesousa and failures are not related. This is good to go.

**Comment by cgmonte** [comment]
ci:forward

**Pull request closed without merging**
