### PR TITLE
LPD-39708 Add visual alerts in the start and end fields of calendar event creation

### PR DESCRIPTION
**Pull request by igor-franca**
Related [ticket](https://liferay.atlassian.net/browse/LPD-39708)
see https://github.com/brianchandotcom/liferay-portal/pull/155836#issuecomment-2455471766

### CODE REVIEW

**Comment by igor-franca** [comment]
Hey @cgmonte, I moved the scripts to a js file. With this, an indentation error was corrected. Can you review my latest commit please?

**Review by cgmonte — APPROVED** [review]
LGTM! To be honest, moving the logic to a JS file and naming it `scheduler_event_validator.js` better organizes the code.

**Comment by igor-franca** [comment]
ci:forward

**Comment by igor-franca** [comment]
ci:test:playwright

**Comment by igor-franca** [comment]
ci:test:playwright

**Pull request closed without merging**
