### PR TITLE
LPD-39726 Back button from Object admin redirects to Default folder (Except Details)

### PR DESCRIPTION
**Pull request by larissacribeiro**
Related Issue: [LPD-39726](https://liferay.atlassian.net/browse/LPD-39726)

This has been previously reviewed and approved here: https://github.com/liferay-bpm/liferay-portal/pull/3771 

[LPD-39726]: https://liferay.atlassian.net/browse/LPD-39726?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

### CODE REVIEW

**Comment by larissacribeiro** [comment]
ci:test:sf

**Comment by larissacribeiro** [comment]
ci:test:relevant

**Comment by larissacribeiro** [comment]
ci:test:object

**Review by linolaoj — APPROVED** [review]

**Comment by larissacribeiro** [comment]
ci:forward:force

**Pull request closed without merging**
