### PR TITLE
LPD-44351 Layout is not rendering correctly after bidding

### PR DESCRIPTION
**Pull request by carolmariaabb**
https://liferay.atlassian.net/browse/LPD-44351

### CODE REVIEW

**Comment by carolmariaabb** [comment]
ci:test:sf

**Review by marcelabc — APPROVED** [review]
LGTM 🎉

**Comment by marcelabc** [comment]
ci:test:relevant

**Comment by marcelabc** [comment]
ci:test:object

**Comment by carolmariaabb** [comment]
ci:test:relevant

**Comment by carolmariaabb** [comment]
ci:report:93269706

**Comment by carolmariaabb** [comment]
ci:report:93272978

**Comment by carolmariaabb** [comment]
ci:forward:force

**Pull request closed without merging**
