### PR TITLE
LPD-44825 Wait for the object relationship promise

### PR DESCRIPTION
**Pull request by igor-franca**
Jira [Ticket](https://liferay.atlassian.net/browse/LPD-44825)

### CODE REVIEW

**Comment by igor-franca** [comment]
ci:test:sf

**Comment by igor-franca** [comment]
ci:test:sf

**Comment by igor-franca** [comment]
ci:test:object

**Comment by larissacribeiro** [comment]
ci:test:relevant

**Review by rebsilva — APPROVED** [review]
LGTM! :cherry_blossom:

**Comment by larissacribeiro** [comment]
ci:report:95269160

**Comment by larissacribeiro** [comment]
ci:forward

**Pull request closed without merging**
