### PR TITLE
LPD-41076

### PR DESCRIPTION
**Pull request by rijema**
Related issue: https://liferay.atlassian.net/browse/LPD-41076

### CODE REVIEW

**Comment by rijema** [comment]
ci:test:sf

**Comment by rijema** [comment]
ci:test:relevant

**Review by marcelabc — APPROVED** [review]
LGTM 🎉

**Comment by marcelabc** [comment]
ci:test:sf

**Comment by marcelabc** [comment]
ci:test:relevant

**Comment by rijema** [comment]
ci:reevaluate:1407401_11928

**Comment by marcelabc** [comment]
ci:report:77096010

**Comment by rijema** [comment]
ci:report:77084987

**Comment by rijema** [comment]
The two unique failures from the relevant reports aren't related. 
PortalLogAssertorTest-modules-integration-mysql57/0/16
PortalLogAssertorTest-modules-integration-mysql57/0/1

**Comment by rijema** [comment]
Just did a rebase and pushed again to avoid discrepancies.

**Comment by rijema** [comment]
Hey @marcelabc , this rebase case is inserted in the one you mentioned?  _"Run the suite again after a rebase with Master"_. If so, I believe it's better to not force the forward.

**Comment by rijema** [comment]
Hi @marcelabc , the unique tests are also failing in my current environment. Yet, the change proposed in this PR is for M:M relationships and the failure is related to a not fetched user. Please see [an example](file:///home/me/dev/projects/liferay-portal/portal-web/tests/classes/com.liferay.poshi.runner.PoshiRunner.html#test[LocalFile.ObjectModelBuilder#CanSearchForObjectDefinitionWithRelationship]):

```
PoshiRunner > [LocalFile.ObjectModelBuilder#CanSearchForObjectDefinitionWithRelationship] > test[LocalFile.ObjectModelBuilder#CanSearchForObjectDefinitionWithRelationship] STANDARD_ERROR
     [exec]     java.lang.Exception: TEST_SETUP_ERROR: No results for path: $['userId']
```

Tbh, I'm not sure about the next step, because this test is passing on Master [as you can see here](https://testray.liferay.com/#/project/35392/routines/1846019/build/76973986/case-result/77086999/history?filter=%7B%22testrayRoutineIds%22%3A%5B1846019%5D%7D&filterSchema=buildResultsHistory) :(

**Comment by marcelabc** [comment]
ci:test:sf

**Comment by marcelabc** [comment]
ci:test:relevant

**Comment by marcelabc** [comment]
ci:test:object

**Comment by marcelabc** [comment]
ci:report:79025817

**Comment by marcelabc** [comment]
ci:test:relevant

**Comment by rijema** [comment]
ci:test:sf

**Comment by rijema** [comment]
ci:test:sf

**Comment by rijema** [comment]
The failed relevant tests are not related to my changes.

**Comment by rijema** [comment]
ci:test:relevant

**Comment by bryceosterhaus** [comment]
ci:test:sf

**Comment by marcelabc** [comment]
ci:test:relevant

**Comment by marcelabc** [comment]
Hey @rijema 
Even though the stable has failed (a known issue), you can check the results using the Testray link.
You can manually forward it to Brian if there are no unique failures.
Thank you!

**Comment by samuelromeiro** [comment]
https://github.com/brianchandotcom/liferay-portal/pull/156742

**Pull request closed without merging**
