### PR TITLE
LPD-38644 No need to initialize the company

### PR DESCRIPTION
**Pull request by carolmariaabb**
https://liferay.atlassian.net/browse/LPD-38644

image

While I couldn't reproduce the failure locally, I suspect that setting the initialization flag to **false** might address the issue. 

- The change is based on the fact that the `CompanyTestUtil.addCompany(true)` is being used in two other tests that are also occasionally failing on Testray with a similar error:

1. [BatchEngineBrokerTest](https://testray.liferay.com/#/project/35392/routines/1288939/build/41790304/case-result/42127845)

image

2. [BatchEngineBundleTrackerTest](https://testray.liferay.com/#/project/35392/routines/1288939/build/41790304/case-result/42127829)

image

**Obs.:** When the initialization flag is set to **true**, the company is created inside a `TransactionInvokerUtil`.

### CODE REVIEW

**Comment by marcelabc** [comment]
ci:test:sf

**Review by marcelabc — APPROVED** [review]
LGTM 🎉

**Comment by marcelabc** [comment]
ci:test:relevant

**Comment by carolmariaabb** [comment]
ci:test:stable

**Comment by carolmariaabb** [comment]
ci:forward:force

**Pull request closed without merging**
