### PR TITLE
LPD-43433 FreeMarker syntax error in notifications with fields of related objects

### PR DESCRIPTION
**Pull request by abesousa**
Related issue: https://issues.liferay.com/browse/LPD-43433

### CODE REVIEW

**Comment by abesousa** [comment]
ci:test:sf

**Review by marcelabc — APPROVED** [review]
LGTM 🎉

**Comment by marcelabc** [comment]
ci:test:relevant

**Comment by marcelabc** [comment]
ci:test:object

**Comment by abesousa** [comment]
ci:report:96120101

**Comment by abesousa** [comment]
ci:forward

**Pull request closed without merging**
