### PR TITLE
LPD-41076 Fix Incorrect search results when looking for related object entries

### PR DESCRIPTION
**Pull request by rebsilva**
Related issue: https://liferay.atlassian.net/browse/LPD-41076

Previous PR: https://github.com/liferay-bpm/liferay-portal/pull/3851

### CODE REVIEW

**Comment by rebsilva** [comment]
ci:test:object

**Comment by rebsilva** [comment]
ci:test:relevant

**Comment by marcelabc** [comment]
ci:report:72043783

**Comment by marcelabc** [comment]
ci:report:72050735

**Comment by marcelabc** [comment]
ci:forward:force

**Pull request closed without merging**
