### PR TITLE
LPD-41018 Make sure the search query parameter is case insensitive in all databases

### PR DESCRIPTION
**Pull request by devpedrotavares**
Related ticket: [LPD-41018](https://liferay.atlassian.net/browse/LPD-41018)

[LPD-41018]: https://liferay.atlassian.net/browse/LPD-41018?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

### CODE REVIEW

**Comment by devpedrotavares** [comment]
ci:test:sf

**Review by linolaoj — APPROVED** [review]

**Comment by devpedrotavares** [comment]
ci:test:relevant

**Comment by devpedrotavares** [comment]
ci:test:object

**Comment by devpedrotavares** [comment]
ci:report:57323394

**Comment by devpedrotavares** [comment]
ci:report:57323953

**Comment by devpedrotavares** [comment]
ci:forward:force

**Pull request closed without merging**
