### PR TITLE
LPD-44638 Select From List field with multiselect is getting only the first value using data providers 

### PR DESCRIPTION
**Pull request by victorKammerer**
Jira ticket: [LPD-44638](https://liferay.atlassian.net/browse/LPD-44638)

[LPD-44638]: https://liferay.atlassian.net/browse/LPD-44638?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

### CODE REVIEW

**Comment by victorKammerer** [comment]
ci:test:sf

**Comment by victorKammerer** [comment]
ci:test:relevant

**Review by MarinhoFeliphe — APPROVED** [review]
LGTM!! :tada:

**Comment by MarinhoFeliphe** [comment]
ci:forward:force

**Pull request closed without merging**
