### PR TITLE
LPD-38663 Removed Liferay Drools assert from poshi test

### PR DESCRIPTION
**Pull request by victorKammerer**
Jira ticket: [LPD-38663](https://liferay.atlassian.net/browse/LPD-38663)

[LPD-38663]: https://liferay.atlassian.net/browse/LPD-38663?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

### CODE REVIEW

**Comment by victorKammerer** [comment]
ci:test:sf

**Comment by victorKammerer** [comment]
ci:test:relevant

**Review by carolmariaabb — APPROVED** [review]

**Comment by carolmariaabb** [comment]
ci:help

**Comment by carolmariaabb** [comment]
ci:test:drools

**Comment by carolmariaabb** [comment]
ci:forward

**Pull request closed without merging**
