### PR TITLE
LPD-28139 - React 18 upgrade for liferay-bpm modules

### PR DESCRIPTION
**Pull request by bryceosterhaus**
Hey, please check out our changes we made to your module for the React 18 upgrade. Particularly, you only need to check out [the commit specifically for your team](https://github.com/liferay-bpm/liferay-portal/pull/3781/commits/7c28386e30ceaa2e5a5c31f850afbe1b0544f662). Please verify this doesn't cause any failures/regressions for you and let me know if you have any questions.

[Our full-pr](https://github.com/liferay-frontend/liferay-portal/pull/4507)

[Updates will be applied to this PR](https://github.com/liferay-frontend/liferay-portal/pull/4533)

---------------------

It's finally here! We'v been working on this on and off over the last year and we've finally got green tests. Upgrading to React 18 is a significant milestone for us because it is the first time we have upgraded out React version. We first added official React support into `liferay-portal` in 2019, and previously we used it sparingly in individual projects. The first supported version of React in Liferay was `16.8.6` and before this upgrade we were at `16.12.0`. Now we are at `18.3.1` which is the latest React release(React 19 already has an RC and we will evaluate that after a general release). [See what is new in React 18](https://react.dev/blog/2022/03/29/react-v18)

### Things to note:
- All of `liferay-portal` now uses React@v18. Our importmap for `react` will point to this new version.
- We also provide importmaps pointing to specific versions. This is particularly helpful for client extensions pointing to importmaps.
```json
// Points to version used in liferay-portal
"react-dom": "/o/frontend-js-react-web/__liferay__/exports/react-dom.js",
"react": "/o/frontend-js-react-web/__liferay__/exports/react.js",

// Version specific
"react-16": "/o/frontend-js-react-web/__liferay__/exports/react-16.js",
"react-dom-16": "/o/frontend-js-react-web/__liferay__/exports/react-dom-16.js",
"react-18": "/o/frontend-js-react-web/__liferay__/exports/react-18.js",
"react-dom-18": "/o/frontend-js-react-web/__liferay__/exports/react-dom-18.js",
```
- React now has [automatic batching](https://react.dev/blog/2022/03/29/react-v18#new-feature-automatic-batching) by default. This will reduce re-renders, but can also possibly cause issues in your app if you are dependent on setState's happening synchronously with re-renders.
- Liferay uses React entirely client-side. We don't get any of the server-side goodies because it requires a Node.js server.
- We added two new APIs in our code to accomodate this change and help teams as they upgrade to React 18. Both of these APIs are an "escape hatch", meaning they allow a you to bypass or override certain constraint at a lower level. These are not normative and the aim is to remove them.
	- `USE_REACT_16` environment variable for running unit tests. When updating to 18 we couldn't just blindly get all the JS unit tests to work. To ensure we move forward smoothly, we added this env variable that is added in your package.json's `test` script. 
	- `__reactDOMFlushSync` boolean prop that can be added to `render` from `frontend-js-react-web` or added as a prop to `react:component` tag. This API should RARELY be used, but it can be used to force React to fallback to render with "non-batching" updates. This is only used sparingly and is only used as an intermediary for teams to update. If you think you need to add this to your code, please reach out to me first and let me check your use case.

### Now what?
If your team owns a module, check the `package.json` script for `test`. If your unit tests are using `USE_REACT_16`, we need you to work on updating your tests to be compatible with React 18. To do this, simply remove that environment variable and check your unit test failures.
#### Preparing for React 19
[See the official React guide](https://react.dev/blog/2024/04/25/react-19-upgrade-guide)

Notable Removals:
- [Removed: `propTypes` and `defaultProps`](https://react.dev/blog/2024/04/25/react-19-upgrade-guide#removed-proptypes-and-defaultprops)
- [Removed: string refs](https://react.dev/blog/2024/04/25/react-19-upgrade-guide#removed-proptypes-and-defaultprops)
- [Removed: `ReactDOM.render`](https://react.dev/blog/2024/04/25/react-19-upgrade-guide#removed-reactdom-render)

Lastly, if you regularly are working with React here at Liferay, please refresh yourself with the [Rules of React](https://react.dev/reference/rules). There were lots of instances where we were updating modules and looking at the React code and there were several patterns that were "anti-react". We highly recommend trying to avoid `useEffect` as much as possible and also avoid `querySelector`, `getElementById`, etc. and `addEventListener` in your apps. Those almost always lead to issues down the road as those happen outside of React's virtual DOM and updating.

### CODE REVIEW

**Comment by samuelromeiro** [comment]
Task to review this PR --> [LPD-40383](https://liferay.atlassian.net/browse/LPD-40383).
It will be included in iteration 24M4#23.

**Comment by bryceosterhaus** [comment]
ci:test:workflow

**Comment by bryceosterhaus** [comment]
ci:test:objects

**Comment by bryceosterhaus** [comment]
ci:test:forms

**Comment by bryceosterhaus** [comment]
ci:test:object

**Comment by bryceosterhaus** [comment]
ci:report:65199564

**Comment by bryceosterhaus** [comment]
note: the current unit tests for data-engine-taglib are failing in this. Not sure why, can your team take a look?

**Comment by marcelabc** [comment]
Hey @cgmonte 
Could you review this PR, please? :smile:

**Comment by bryceosterhaus** [comment]
FYI I am still seeing issues in data-engine-taglib that are causing issues in the unit tests

**Comment by bryceosterhaus** [comment]
ci:test:workflow

**Comment by bryceosterhaus** [comment]
ci:test:objects

**Comment by marcelabc** [comment]
Hi @bryceosterhaus :smile: 
I saw that you pushed some commits in this PR. Is there a new commit, or are you just fixing rebase errors?

**Comment by bryceosterhaus** [comment]
Rebased on latest and pushed changes. Also reran tests.On Nov 25, 2024, at 4:10 PM, Marcela Cunha ***@***.***> wrote:﻿
Hi @bryceosterhaus 😄
I saw that you pushed some commits in this PR. Is there a new commit, or are you just fixing rebase errors?

**Comment by bryceosterhaus** [comment]
@marcelabc any update when this will be reviewed? At a minimum we just need to know what failures are legit, because I haven't been able to reproduce any failures in the UI itself manually.

**Comment by igor-franca** [comment]
Hey @bryceosterhaus, I'll take a look at this.

**Comment by bryceosterhaus** [comment]
ci:report:76393330

**Comment by bryceosterhaus** [comment]
ci:report:76427876

**Comment by bryceosterhaus** [comment]
@igor-franca please let me know if you make any diagnosis today. We are primarily concerned with finding failures that are reproducible with manual testing so that we can fix any issues with React 18.

**Comment by igor-franca** [comment]
Hey @bryceosterhaus, I'm starting with the forms analysis. I will run the tests locally, I will try to perform the steps manually in the application for those that fail. 

You can follow my progress [here](https://docs.google.com/spreadsheets/d/1fknwpm3X0j8hHSuTsr51w_yCpUTgjAHkleRE5cEqpG0/edit?usp=sharing)

**Comment by bryceosterhaus** [comment]
Thanks @igor-franca. Just to clarify as well, it is okay for unit tests to use the `USE_REACT_16=true` flag. There is no need to force unit tests to use 16 or 18, whatever allows them to pass right now is fine.

Our primary concern is end user functionality. If manual testing is passing, we can forward and then fix flakey tests after this is merged.

**Comment by bryceosterhaus** [comment]
latest runs of stable(for unit tests) is [passing here](https://github.com/liferay-frontend/liferay-portal/pull/4507).

So now we just need to know whether any of the functional tests are legit and manually reproducible

**Comment by igor-franca** [comment]
ci:report:65224039

**Comment by igor-franca** [comment]
Hey @bryceosterhaus, sorry for the delay. I managed to finish analyzing the tests.

In general, the forms and objects routine was analyzed since the workflow tests had already been previously investigated and corrected.

Regarding objects, I couldn't find any related failures, I ran a robust set of tests and everything went well.
Regarding the form, I also couldn't find any flaw in the application that was related to the changes. 

However, I noticed that we are not using the `USE_REACT_16=true` flag in data-engine-taglib's `packege.json`, even though this corrects a large number of tests, is there any reason for this?

Even after adding this flag locally, some tests in the `Editor.es.js` file continued to fail. I did manual tests on the functionalities involved (forms rules) and everything worked well. So I believe we will need to correct these tests in the future, correct @samuelromeiro?

More details about the analysis, [here](https://docs.google.com/spreadsheets/d/1fknwpm3X0j8hHSuTsr51w_yCpUTgjAHkleRE5cEqpG0/edit?usp=sharing)

**Comment by samuelromeiro** [comment]
Hey @igor-franca, I'm going to share this with @gabrielwas and @linolaoj so they decide. 
Thank you for the analysis.

**Comment by linolaoj** [comment]
Hi @igor-franca, I understand that no bugs were found and we would need to create a separate task to fix the remaining tests that are failing due to the react upgrade. This approach sounds good to me. 
Thank you.

**Comment by bryceosterhaus** [comment]
thanks for the review! Just note that it is fine for unit tests to use `USE_REACT_16=true` or not. Either way is fine, although ideally we make an effort to remove that flag and unit test with react 18. Using the flag shouldn't block the PR though.

closing in favor of https://github.com/liferay-frontend/liferay-portal/pull/4507. I will forward from that PR

**Comment by bryceosterhaus** [comment]
> However, I noticed that we are not using the USE_REACT_16=true flag in data-engine-taglib's packege.json, even though this corrects a large number of tests, is there any reason for this?

This typically indicates flakey application code or flakey tests. Bad application code would be somethign typically related to "re-renders" and the application being dependent on a specific number of re-renders. This is bad because applications should be resilient and be deterministic based on the props provided.

**Pull request closed without merging**
