### PR TITLE
LPD-42003 Add name property on nested fields

### PR DESCRIPTION
**Pull request by rebsilva**
Related issues:
- https://liferay.atlassian.net/browse/LPP-56575
- https://liferay.atlassian.net/browse/LPD-42003

### CODE REVIEW

**Comment by rebsilva** [comment]
@cgmonte i will run the tests to make sure the solution is not breaking anything; also, i will need to send this for content management team to review the test

**Comment by rebsilva** [comment]
ci:test:sf

**Comment by rebsilva** [comment]
ci:test:relevant

**Comment by rebsilva** [comment]
ci:test:data-engine

**Comment by rebsilva** [comment]
ci:test:forms

**Comment by rebsilva** [comment]
ci:test:web-content

**Comment by rebsilva** [comment]
page-management-playwright

**Comment by rebsilva** [comment]
ci:test:page-management-playwright

**Comment by rebsilva** [comment]
ci:test:content-management-playwright

**Review by cgmonte — APPROVED** [review]
LGTM!

**Comment by cgmonte** [comment]
ci:report:67416230

**Comment by cgmonte** [comment]
ci:report:67888792

**Comment by cgmonte** [comment]
ci:forward

**Pull request closed without merging**
