### PR TITLE
LPD-39833  - Technical Task | Add ERC column in KaleoDefinition table entity

### PR DESCRIPTION
**Pull request by JhossephG**
First task from story [LPD-36879](https://liferay.atlassian.net/browse/LPD-36879).

Here we added the ERC column in the KaleoDefinition table entity and expose it in the headless api. We will use it in the next task from the story. 

[LPD-36879]: https://liferay.atlassian.net/browse/LPD-36879?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

### CODE REVIEW

**Comment by JhossephG** [comment]
ci:test:sf

**Comment by JhossephG** [comment]
ci:test:sf

**Comment by JhossephG** [comment]
ci:test:relevant

**Comment by JhossephG** [comment]
ci:test:sf

**Comment by JhossephG** [comment]
ci:test:relevant

**Comment by linolaoj** [comment]
Hi @JhossephG , since the ci already ran on the previous pr, you can forward this one manually.

**Comment by JhossephG** [comment]
sent [here](https://github.com/brianchandotcom/liferay-portal/pull/155702)

**Pull request closed without merging**
