### PR TITLE
LPD-39701 - "Copy" button overflows in Notification templates table

### PR DESCRIPTION
**Pull request by ilzamcmed**
Ticket: https://liferay.atlassian.net/browse/LPD-39701
Original PR: https://github.com/liferay-platform-experience/liferay-portal/pull/803

## Motivation
Fix overflowing button in Notification templates

## Proposed Solution
This proposed solution is to remove the text `copy` and add the icon equivalent. 
## Steps to Verify

1. Enable FF: LPS-193005.
2.  Navigate to the Notification templates section under control panel
3. Locate the table displaying notification templates
4. Observe the "Copy" CTA button in the table

## Screenshots/videos 
image

### CODE REVIEW

**Comment by ilzamcmed** [comment]
ci:test:sf

**Comment by ilzamcmed** [comment]
ci:test:relevant

**Review by cgmonte — APPROVED** [review]
LGTM!

**Comment by cgmonte** [comment]
ci:help

**Comment by cgmonte** [comment]
ci:test:object

**Comment by cgmonte** [comment]
ci:test:playwright

**Comment by ilzamcmed** [comment]
I am looking into the failures.

**Comment by ethib137** [comment]
ci:report:77952691

**Comment by ilzamcmed** [comment]
The failures seams to be unrelated with these changes.
@cgmonte

**Comment by cgmonte** [comment]
> The failures seem to be unrelated to these changes. @cgmonte

Yes, it does seem like they are not related to the changes I will forward this.

**Comment by cgmonte** [comment]
ci:forward

**Pull request closed without merging**
