### PR TITLE
LPD-41062 Create new inheritance column on object admin table and add related label to edit object definition

### PR DESCRIPTION
**Pull request by larissacribeiro**
Related tickets: [LPD-41062](https://liferay.atlassian.net/browse/LPD-41062),  [LPD-41063](https://liferay.atlassian.net/browse/LPD-41063) and [LPD-41134)](https://liferay.atlassian.net/browse/LPD-41134)

Needed FF: _feature.flag.LPS-187142=true_ and _feature.flag.LPS-193005=true_

[LPD-41062]: https://liferay.atlassian.net/browse/LPD-41062?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[LPD-41063]: https://liferay.atlassian.net/browse/LPD-41063?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

### CODE REVIEW

**Comment by larissacribeiro** [comment]
ci:test:sf

**Comment by rebsilva** [comment]
just started reviewing! :cherry_blossom:

**Comment by larissacribeiro** [comment]
hey @rebsilva, thanks! I'm pushing another commit here, okay?

**Review by rebsilva — APPROVED** [review]
LGTM! :tada: :cherry_blossom: great work on this story @larissacribeiro!

**Comment by rebsilva** [comment]
ci:test:sf

**Comment by rebsilva** [comment]
ci:test:object

**Comment by rebsilva** [comment]
ci:test:playwright

**Comment by larissacribeiro** [comment]
ci:test:playwright

**Comment by larissacribeiro** [comment]
ci:test:relevant

**Comment by larissacribeiro** [comment]
ci:test:object

**Comment by larissacribeiro** [comment]
rerunning the suites because there were a lot of failures related to time out.

**Comment by larissacribeiro** [comment]
failures are unrelated 🙏🏾

**Comment by larissacribeiro** [comment]
ci:forward:force

**Pull request closed without merging**
