### PR TITLE
LPD-41068 Prioritize structure ERC and group ERC during Import and Export form widget process (without Feature Flag LPD-34651)

### PR DESCRIPTION
**Pull request by p-albuquerque**
Related issue: https://issues.liferay.com/browse/LPD-41068

### CODE REVIEW

**Comment by p-albuquerque** [comment]
ci:test:relevant

**Comment by marcelabc** [comment]
ci:test:forms

**Comment by marcelabc** [comment]
ci:report:75020885

**Comment by p-albuquerque** [comment]
ci:report:76659206

**Comment by p-albuquerque** [comment]
ci:forward:force

**Pull request closed without merging**
