### PR TITLE
LPD-41167 Pre-populate some data related to object definition to avoid extra SQL calls

### PR DESCRIPTION
**Pull request by pedro-oliveira446**
[LPD-41346](https://liferay.atlassian.net/browse/LPD-41346)
[LPD-41167](https://liferay.atlassian.net/browse/LPD-41167)

@guilhermedcamacho 

see the Tina's comment https://github.com/liferay-core-infra/liferay-portal/pull/7623#issuecomment-2469372794

[LPD-41167]: https://liferay.atlassian.net/browse/LPD-41167?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[LPD-41167]: https://liferay.atlassian.net/browse/LPD-41167?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[LPD-41346]: https://liferay.atlassian.net/browse/LPD-41346?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

### CODE REVIEW

**Comment by pedro-oliveira446** [comment]
ci:test:relevant

**Comment by pedro-oliveira446** [comment]
ci:test:object

**Comment by pedro-oliveira446** [comment]
ci:test:relevant

**Comment by pedro-oliveira446** [comment]
ci:test:object

**Comment by pedro-oliveira446** [comment]
ci:test:sf

**Comment by pedro-oliveira446** [comment]
ci:test:relevant

**Comment by pedro-oliveira446** [comment]
ci:report:67690718

**Review by guilhermedcamacho — APPROVED** [review]

**Comment by pedro-oliveira446** [comment]
Resent https://github.com/liferay-core-infra/liferay-portal/pull/7640

**Pull request closed without merging**
