### PR TITLE
LPD-41426 Fix BigDecimal conversion error when result is empty

### PR DESCRIPTION
**Pull request by riccardo-alberti**
Related issue: https://liferay.atlassian.net/browse/LPD-41426

### CODE REVIEW

**Comment by marcelabc** [comment]
ci:test:sf

**Comment by marcelabc** [comment]
ci:test:relevant

**Comment by marcelabc** [comment]
ci:report:61743704

**Comment by marcelabc** [comment]
Hi @riccardo-alberti,
I could not reproduce the issue. I slack you and wrote a comment for you in the ticket.
Thank you!

**Comment by samuelromeiro** [comment]
Issue no longer reproducible. 
Closing the PR!

**Pull request closed without merging**
