### PR TITLE
[Fire LPP-56152] LPD-39828

### PR DESCRIPTION
**Pull request by vngoliveira**
[LPP-56152](https://liferay.atlassian.net/browse/LPP-56152)
[LPD-39828](https://liferay.atlassian.net/browse/LPD-39828)

Reason why I am resending: https://github.com/brianchandotcom/liferay-portal/pull/155428#issuecomment-2427844503

[LPP-56152]: https://liferay.atlassian.net/browse/LPP-56152?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[LPD-39828]: https://liferay.atlassian.net/browse/LPD-39828?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

### CODE REVIEW

**Comment by vngoliveira** [comment]
ci:test:sf

**Comment by vngoliveira** [comment]
ci:test:relevant

**Comment by vngoliveira** [comment]
ci:test:workflow

**Comment by vngoliveira** [comment]
ci:test:relevant

**Comment by vngoliveira** [comment]
ci:test:sf

**Comment by vngoliveira** [comment]
ci:test:workflow

**Comment by vngoliveira** [comment]
ci:test:sf

**Review by linolaoj — APPROVED** [review]

**Comment by linolaoj** [comment]
ci:forward

**Pull request closed without merging**
