### PR TITLE
LPD-39492 Revert LPD-38769

### PR DESCRIPTION
**Pull request by devpedrotavares**
Related ticket: [LPD-39492](https://liferay.atlassian.net/browse/LPD-39492)

[LPD-39492]: https://liferay.atlassian.net/browse/LPD-39492?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

### CODE REVIEW

**Comment by devpedrotavares** [comment]
ci:test:object

**Comment by devpedrotavares** [comment]
ci:test:relevant

**Comment by devpedrotavares** [comment]
ci:report:49479136

**Comment by devpedrotavares** [comment]
ci:report:49479136

**Review by linolaoj — APPROVED** [review]

**Comment by linolaoj** [comment]
ci:test:object

**Comment by devpedrotavares** [comment]
ci:report:50400406

**Comment by devpedrotavares** [comment]
ci:forward:force

**Comment by carolmariaabb** [comment]
ci:forward:force

**Pull request closed without merging**
