### PR TITLE
LPD-44332 Fix permissions when descendant nodes have standalone object actions

### PR DESCRIPTION
**Pull request by carolmariaabb**
https://liferay.atlassian.net/browse/LPD-44332

### CODE REVIEW

**Comment by carolmariaabb** [comment]
ci:test:sf

**Review by marcelabc — APPROVED** [review]
LGTM 🎉

**Comment by marcelabc** [comment]
ci:test:relevant

**Comment by marcelabc** [comment]
ci:test:object

**Comment by carolmariaabb** [comment]
ci:report:93272984

**Comment by carolmariaabb** [comment]
ci:report:93304084

**Comment by carolmariaabb** [comment]
ci:forward:force

**Pull request closed without merging**
