### PR TITLE
LPD-42714 Object View Filtering drops and error when Filter has a Multiple Picklist Field

### PR DESCRIPTION
**Pull request by pedro-oliveira446**
[LPD-42714](https://liferay.atlassian.net/browse/LPD-42714)

[LPD-42714]: https://liferay.atlassian.net/browse/LPD-42714?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

### CODE REVIEW

**Review by linolaoj — APPROVED** [review]

**Comment by pedro-oliveira446** [comment]
ci:test:object

**Comment by pedro-oliveira446** [comment]
ci:test:relevant

**Comment by pedro-oliveira446** [comment]
ci:test:object

**Comment by pedro-oliveira446** [comment]
ci:test:sf

**Comment by pedro-oliveira446** [comment]
ci:report:76455237

**Comment by pedro-oliveira446** [comment]
ci:report:76455237

**Comment by pedro-oliveira446** [comment]
ci:forward:force

**Pull request closed without merging**
