### PR TITLE
LPD-43202 Pass empty string as default to avoid NPE on jspWriter.write

### PR DESCRIPTION
**Pull request by devpedrotavares**
Related ticket: [LPD-43202](https://liferay.atlassian.net/browse/LPD-43202)

This fixes an existing [test](https://github.com/liferay/liferay-portal/blob/master/modules/test/playwright/tests/object-web/objectEntries.spec.ts#L786)

[LPD-43202]: https://liferay.atlassian.net/browse/LPD-43202?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

### CODE REVIEW

**Review by linolaoj — APPROVED** [review]

**Comment by devpedrotavares** [comment]
ci:test:relevant

**Comment by devpedrotavares** [comment]
ci:test:object

**Comment by devpedrotavares** [comment]
ci:test:object

**Comment by devpedrotavares** [comment]
ci:test:relevant

**Comment by devpedrotavares** [comment]
ci:test:relevant

**Comment by devpedrotavares** [comment]
ci:test:relevant

**Comment by devpedrotavares** [comment]
ci:test:sf

**Comment by devpedrotavares** [comment]
Just did a rebase on top of the newest master branch to see if that fixes CI

**Comment by devpedrotavares** [comment]
ci:test:object

**Comment by devpedrotavares** [comment]
ci:report:83030190

**Comment by devpedrotavares** [comment]
ci:report:83031000

**Comment by devpedrotavares** [comment]
ci:forward:force

**Comment by devpedrotavares** [comment]
ci:forward

**Comment by devpedrotavares** [comment]
ci:report:83664797

**Comment by devpedrotavares** [comment]
ci:forward:force

**Comment by devpedrotavares** [comment]
ci:report:83664797

**Comment by devpedrotavares** [comment]
Forwarded manually since stable won't collaborate: https://github.com/brianchandotcom/liferay-portal/pull/156679

**Pull request closed without merging**
