### PR TITLE
LPD-41076

### PR DESCRIPTION
**Pull request by rijema**
Related issue: https://liferay.atlassian.net/browse/LPD-41076

### CODE REVIEW

**Review by cgmonte — COMMENTED** [review]
The test is quite long and we can save two lines by removing two unnecessary variables created in the test body, but I won't mark this as request for change. You can move forward the way it is, but if you have the time, please remove those two lines. Check comments. Cheers!

**Review by cgmonte — APPROVED** [review]
LGTM!

**Comment by marcelabc** [comment]
Just started reviewing :)

**Comment by marcelabc** [comment]
resent: https://github.com/liferay-bpm/liferay-portal/pull/3851

**Pull request closed without merging**
