### PR TITLE
LPD-39434 Fix date engine poshi test

### PR DESCRIPTION
**Pull request by igor-franca**
Related [Ticket](https://liferay.atlassian.net/browse/LPD-39434)

### CODE REVIEW

**Comment by igor-franca** [comment]
ci:test:sf

**Comment by igor-franca** [comment]
ci:test:data-engine

**Review by rebsilva — APPROVED** [review]
LGTM! :cherry_blossom:

**Comment by igor-franca** [comment]
ci:forward

**Pull request closed without merging**
