### PR TITLE
LPD-39833 - Technical Task | Add ERC column in KaleoDefinition table entity 

### PR DESCRIPTION
**Pull request by JhossephG**
First task from story [LPD-36879](https://liferay.atlassian.net/browse/LPD-36879).

Here we added the ERC column in the KaleoDefinition table entity to use it in the next task from the story.

[LPD-36879]: https://liferay.atlassian.net/browse/LPD-36879?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

### CODE REVIEW

**Comment by JhossephG** [comment]
ci:test:sf

**Comment by JhossephG** [comment]
ci:test:relevant

**Comment by JhossephG** [comment]
ci:test:workflow

**Review by linolaoj — CHANGES_REQUESTED** [review]
@JhossephG , the second build service commit looks like a build rest. Can you please change the commit message?

**Comment by JhossephG** [comment]
reopened [here](https://github.com/liferay-bpm/liferay-portal/pull/3791)

**Comment by JhossephG** [comment]
reopened https://github.com/liferay-bpm/liferay-portal/pull/3791

**Pull request closed without merging**
