### PR TITLE
LPD-38580 Fix tests due the Manage Translations change on Web Content

### PR DESCRIPTION
**Pull request by rebsilva**
Related issue: https://liferay.atlassian.net/browse/LPD-38580

resent from https://github.com/liferay-bpm/liferay-portal/pull/3772

### CODE REVIEW

**Comment by rebsilva** [comment]
ci:test:sf

**Comment by rebsilva** [comment]
ci:test:data-engine

**Comment by rebsilva** [comment]
ci:test:sf

**Comment by igor-franca** [comment]
The changes seem correct, let's wait for the test results 😄

**Comment by igor-franca** [comment]
ci:test:data-engine

**Comment by rebsilva** [comment]
from what i saw, more than 40 tests that were failing are now passing :pray: there are still some tests failing that may be related to this, but i think we can forward this PR to stabilize the data-engine suite while fixing the remaining tests.

do you agree @igor-franca?

**Review by igor-franca — APPROVED** [review]
We can continue like this Rebeca, just remember to close only the tasks related to the tests that were corrected.

Whoever gets free first can take the remaining tests next.

**Comment by rebsilva** [comment]
great, i will do that!

**Comment by rebsilva** [comment]
ci:forward

**Pull request closed without merging**
