### PR TITLE
LPD-39307 [Test fix] com.liferay.portal.workflow.kaleo.internal.runtime.integration.test.WorkflowTaskManagerImplTest

### PR DESCRIPTION
**Pull request by pedro-oliveira446**
[LPD-39316](https://liferay.atlassian.net/browse/LPD-39316)

[LPD-39316]: https://liferay.atlassian.net/browse/LPD-39316?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

### CODE REVIEW

**Comment by pedro-oliveira446** [comment]
ci:test:sf

**Comment by pedro-oliveira446** [comment]
ci:test:relevant

**Comment by pedro-oliveira446** [comment]
ci:test:object

**Review by linolaoj — APPROVED** [review]

**Comment by pedro-oliveira446** [comment]
Resent https://github.com/brianchandotcom/liferay-portal/pull/155177

**Pull request closed without merging**
