### PR TITLE
LPD-43348

### PR DESCRIPTION
**Pull request by vngoliveira**
[LPD-43348](https://liferay.atlassian.net/browse/LPD-43348)

[LPD-43348]: https://liferay.atlassian.net/browse/LPD-43348?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

### CODE REVIEW

**Comment by vngoliveira** [comment]
ci:test:sf

**Comment by guilhermedcamacho** [comment]
Hey @MarinhoFeliphe, any news about this review?

**Comment by MarinhoFeliphe** [comment]
@guilhermedcamacho I'm changing the fix, as soon as I finish I'll resent and close this pull request.

**Comment by MarinhoFeliphe** [comment]
Resent here: https://github.com/liferay-bpm/liferay-portal/pull/3950

cc: @guilhermedcamacho

**Pull request closed without merging**
