### PR TITLE
LPD-44387 Add Upgrade Process [Follow-up]

### PR DESCRIPTION
**Pull request by vngoliveira**
[LPP-57067](https://liferay.atlassian.net/browse/LPP-57067)

[LPP-57067]: https://liferay.atlassian.net/browse/LPP-57067?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

### CODE REVIEW

**Comment by vngoliveira** [comment]
ci:test:sf

**Review by carolmariaabb — CHANGES_REQUESTED** [review]
@vngoliveira just a few things:

1. For the LPP you would have to create a groovy script to update the customer database. Please align this with @gabrielwas.
2. Please create the upgrade test

**Comment by vngoliveira** [comment]
ci:test:sf

**Comment by carolmariaabb** [comment]
@vngoliveira please see https://github.com/liferay-bpm/liferay-portal/pull/3999

**Pull request closed without merging**
