### PR TITLE
LPD-42973 Add inheritance checkbox to relationship sidebar, update node/edge styles and show disable inheritance modal

### PR DESCRIPTION
**Pull request by larissacribeiro**
Related Issues: [LPD-42973](https://liferay.atlassian.net/browse/LPD-42973), [LPD-42970](https://liferay.atlassian.net/browse/LPD-42970), [LPD-42971](https://liferay.atlassian.net/browse/LPD-42971) and [LPD-43492](https://liferay.atlassian.net/browse/LPD-43492)

[LPD-42973]: https://liferay.atlassian.net/browse/LPD-42973?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[LPD-42970]: https://liferay.atlassian.net/browse/LPD-42970?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[LPD-42971]: https://liferay.atlassian.net/browse/LPD-42971?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[LPD-43492]: https://liferay.atlassian.net/browse/LPD-43492?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

### CODE REVIEW

**Comment by larissacribeiro** [comment]
ci:test:sf

**Comment by larissacribeiro** [comment]
@rebsilva when you review this pr, can you consider only the last four commits, please? thank you!! ❤️

**Comment by rebsilva** [comment]
sure! i will take a look soon, thanks!

**Comment by rebsilva** [comment]
just started reviewing! :cherry_blossom:

**Review by rebsilva — APPROVED** [review]
LGTM! :cherry_blossom: great work @larissacribeiro! :bear:

**Comment by rebsilva** [comment]
ci:test:relevant

**Comment by rebsilva** [comment]
ci:test:object

**Comment by larissacribeiro** [comment]
ci:test:sf

**Comment by larissacribeiro** [comment]
ci:test:object

**Comment by larissacribeiro** [comment]
hi @rebsilva! just letting you know, I haven't changed anything on the commits, just removed the ones from Carlos and rebased the branch. thank you!

**Comment by larissacribeiro** [comment]
ci:report:85955493

**Comment by larissacribeiro** [comment]
Failures are unrelated

**Comment by larissacribeiro** [comment]
ci:forward:force

**Pull request closed without merging**
