### PR TITLE
LPD-38769

### PR DESCRIPTION
**Pull request by JhossephG**
[LPD-38769](https://liferay.atlassian.net/browse/LPD-38769)

[LPD-38769]: https://liferay.atlassian.net/browse/LPD-38769?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

### CODE REVIEW

**Comment by JhossephG** [comment]
ci:test:sf

**Comment by MarinhoFeliphe** [comment]
ci:test:sf

**Comment by MarinhoFeliphe** [comment]
ci:test:object

**Comment by JhossephG** [comment]
ci:test:relevant

**Comment by JhossephG** [comment]
ci:test:object

**Review by MarinhoFeliphe — APPROVED** [review]
LGTM!! :tada:

**Comment by MarinhoFeliphe** [comment]
Resent here: https://github.com/brianchandotcom/liferay-portal/pull/155176

**Comment by gabrielwas** [comment]
@MarinhoFeliphe @JhossephG The test ObjectFields#CanCreateEntryWithAggregationField failed in this test:object run (for the first time) and the PR was still forwarded. We need to keep our eyes on the suite results.

**Comment by JhossephG** [comment]
> @MarinhoFeliphe @JhossephG The test ObjectFields#CanCreateEntryWithAggregationField failed in this test:object run (for the first time) and the PR was still forwarded. We need to keep our eyes on the suite results.
> 
> cc @linolaoj

Sorry @gabrielwas , I only noticed the behavior after sent it. It was fixed in this follow up here: https://github.com/liferay-bpm/liferay-portal/pull/3761.

**Pull request closed without merging**
