### PR TITLE
LPD-41563 Create unit/functional tests

### PR DESCRIPTION
**Pull request by larissacribeiro**
Related Issues: [LPD-41563](https://liferay.atlassian.net/browse/LPD-41563)

[LPD-41563]: https://liferay.atlassian.net/browse/LPD-41563?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

### CODE REVIEW

**Comment by larissacribeiro** [comment]
ci:test:sf

**Comment by igor-franca** [comment]
Hey @larissacribeiro, could you define the reviewer and sign him?

**Comment by larissacribeiro** [comment]
Hey @igor-franca, I wanted to align first with the other fronts devs who had fewer things on their queue. I talked to Carlos and I will assign it to Rebeca now, thanks!

**Comment by larissacribeiro** [comment]
@rebsilva could you please review only the last three commits on this pr? It has an dependency on the playwright test commit of Igor's [pr](https://github.com/liferay-bpm/liferay-portal/pull/3842), so that's why it's here as well. Thanks!! 🌷

**Comment by larissacribeiro** [comment]
ci:test:sf

**Comment by larissacribeiro** [comment]
ci:test:object

**Comment by larissacribeiro** [comment]
image
The tests have passed 🙏🏾 Igor's wont pass here since the feature He developed is not on this branch!

**Comment by rebsilva** [comment]
sure, i'm taking a look now!

**Comment by igor-franca** [comment]
Thank you Rebecca! How I worked together with Larissa on unit tests. I would like a third opinion 😄

**Review by rebsilva — APPROVED** [review]
LGTM! :tada: :cherry_blossom:

**Comment by larissacribeiro** [comment]
ci:test:sf

**Comment by larissacribeiro** [comment]
ci:test:relevant

**Comment by larissacribeiro** [comment]
ci:test:sf

**Comment by larissacribeiro** [comment]
ci:test:relevant

**Comment by larissacribeiro** [comment]
ci:forward:force

**Pull request closed without merging**
