### PR TITLE
LPD-38680 Ensure tree max height will not be exceeded

### PR DESCRIPTION
**Pull request by pedro-oliveira446**
Related: https://liferay.atlassian.net/browse/LPD-38680

### CODE REVIEW

**Review by marcelabc — APPROVED** [review]
LGTM 🎉

**Comment by marcelabc** [comment]
ci:test:sf

**Comment by pedro-oliveira446** [comment]
ci:test:sf

**Comment by pedro-oliveira446** [comment]
ci:test:relevant

**Comment by pedro-oliveira446** [comment]
ci:test:object

**Comment by marcelabc** [comment]
ci:report:40945772

**Comment by marcelabc** [comment]
ci:report:41006967

**Comment by marcelabc** [comment]
Hey @pedro-oliveira446, can you please analyze the results? Thank you!

**Comment by pedro-oliveira446** [comment]
Resent https://github.com/brianchandotcom/liferay-portal/pull/155174

**Pull request closed without merging**
