### PR TITLE
LPD-39823 Fix filter with status object field. Using 'any' causes error

### PR DESCRIPTION
**Pull request by devpedrotavares**
Related ticket: [LPD-39823](https://liferay.atlassian.net/browse/LPD-39823)

[LPD-39823]: https://liferay.atlassian.net/browse/LPD-39823?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

### CODE REVIEW

**Review by MarinhoFeliphe — CHANGES_REQUESTED** [review]
@devpedrotavares, it seems that a break change was introduced changing the type of the status from collection of int to an int, right?

could you please confirm if the `int` entity field type supports the `in` operator, if so please remove this conditional that handles the status field, otherwise you can consider this changes approved on my side if there are already a test covering this use case.

Thank you!

**Comment by devpedrotavares** [comment]
> @devpedrotavares, it seems that a break change was introduced changing the type of the status from collection of int to an int, right?
> 
> could you please confirm if the `int` entity field type supports the `in` operator, if so please remove this conditional that handles the status field, otherwise you can consider this changes approved on my side if there are already a test covering this use case.
> 
> Thank you!

I tried removing the conditional, but it fails. The types are still incompatible.

Thank you!

**Comment by devpedrotavares** [comment]
ci:forward

**Comment by devpedrotavares** [comment]
ci:forward:force

**Pull request closed without merging**
