### PR TITLE
LPD-41851 Migrate tag liferay-ui:icon-menu to clay:dropdown-actions

### PR DESCRIPTION
**Pull request by devpedrotavares**
Related ticket: [LPD-41851](https://liferay.atlassian.net/browse/LPD-41851)

[LPD-41851]: https://liferay.atlassian.net/browse/LPD-41851?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

### CODE REVIEW

**Review by MarinhoFeliphe — APPROVED** [review]
LGTM!! :tada:

**Comment by MarinhoFeliphe** [comment]
ci:test:relevant

**Comment by MarinhoFeliphe** [comment]
ci:test:workflow

**Comment by devpedrotavares** [comment]
ci:report:66545274

**Comment by devpedrotavares** [comment]
ci:test:relevant

**Comment by devpedrotavares** [comment]
I added a commit to fix a related failures. I reran the tests to make sure they fix the failures. Because I had an issue running the tests locally

**Comment by devpedrotavares** [comment]
ci:test:workflow

**Comment by devpedrotavares** [comment]
The tests are now passing

**Comment by devpedrotavares** [comment]
ci:test:workflow

**Comment by devpedrotavares** [comment]
ci:report:67940117

**Comment by devpedrotavares** [comment]
ci:test:workflow

**Comment by devpedrotavares** [comment]
ci:test:workflow

**Comment by devpedrotavares** [comment]
ci:report:68773110

**Comment by devpedrotavares** [comment]
ci:report:68773110

**Comment by devpedrotavares** [comment]
ci:test:workflow

**Comment by devpedrotavares** [comment]
ci:report:68997992

**Comment by devpedrotavares** [comment]
Hi @MarinhoFeliphe , the tests are now passing again, can you please review the test fixes?

**Review by MarinhoFeliphe — APPROVED** [review]
LGTM!! :tada:

**Comment by MarinhoFeliphe** [comment]
ci:forward

**Comment by devpedrotavares** [comment]
ci:test:sf

**Comment by devpedrotavares** [comment]
ci:test:sf

**Comment by devpedrotavares** [comment]
ci:test:relevant

**Comment by devpedrotavares** [comment]
Hi @MarinhoFeliphe , I added this last [commit](https://github.com/liferay-bpm/liferay-portal/pull/3853/commits/86f4cd7c2076e9e122d49f76f53aef8725c9d47d) adding a test to fully cover this scenario.

**Comment by MarinhoFeliphe** [comment]
ci:forward

**Review by MarinhoFeliphe — APPROVED** [review]
LGTM!! :tada:

**Pull request closed without merging**
