### PR TITLE
LPD-43173

### PR DESCRIPTION
**Pull request by guilhermedcamacho**

### CODE REVIEW

**Comment by guilhermedcamacho** [comment]
ci:test:sf

**Comment by guilhermedcamacho** [comment]
ci:test:relevant

**Comment by guilhermedcamacho** [comment]
ci:test:workflow

**Comment by JhossephG** [comment]
ci:test:relevant

**Comment by JhossephG** [comment]
resent [here](https://github.com/liferay-bpm/liferay-portal/pull/3992)

**Pull request closed without merging**
