### PR TITLE
LPD-41969 Missing CDATA content for empty web content fields

### PR DESCRIPTION
**Pull request by icgsbr**
https://liferay.atlassian.net/browse/LPD-41969

### CODE REVIEW

**Comment by icgsbr** [comment]
ci:test:sf

**Comment by marcelabc** [comment]
Just started reviewing :)

**Comment by marcelabc** [comment]
@icgsbr, always remember to run the tests locally, including the new and existing ones. You should make sure that your fix keeps the other scenarios intact. 

This happened in this PR.

**Comment by marcelabc** [comment]
Please review https://github.com/liferay-bpm/liferay-portal/pull/3881 and ask me questions if you need help understanding.

**Pull request closed without merging**
