### PR TITLE
LPD-43708 Change error messages

### PR DESCRIPTION
**Pull request by igor-franca**
Jira [ticket](https://liferay.atlassian.net/browse/LPD-43708)
Resending from [here](https://github.com/brianchandotcom/liferay-portal/pull/156999)

### CODE REVIEW

**Comment by igor-franca** [comment]
ci:test:sf

**Comment by igor-franca** [comment]
ci:test:relevant

**Comment by igor-franca** [comment]
The updated test was [successful](https://testray.liferay.com/#/project/35392/routines/45357/build/91887353/case-result/91893822) in CI

**Comment by igor-franca** [comment]
Running the CI again to try to receive a satisfactory result in the stable

**Comment by igor-franca** [comment]
ci:test:stable

**Comment by igor-franca** [comment]
ci:stop

**Comment by igor-franca** [comment]
ci:stop

**Comment by igor-franca** [comment]
ci:test:relevant

**Comment by carolmariaabb** [comment]
ci:report:93085881

**Comment by carolmariaabb** [comment]
ci:report:93085881

**Comment by carolmariaabb** [comment]
ci:forward:force

**Comment by marcelabc** [comment]
ci:forward:force

**Comment by igor-franca** [comment]
ci:stop

**Comment by igor-franca** [comment]
ci:forward:force

**Pull request closed without merging**
