### PR TITLE
LPD-43532 No accessibility feedback when the event creation pop-up is open on the screen

### PR DESCRIPTION
**Pull request by larissacribeiro**
Related Issue: [LPD-43532](https://liferay.atlassian.net/browse/LPD-43532)

[LPD-43532]: https://liferay.atlassian.net/browse/LPD-43532?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

### CODE REVIEW

**Comment by larissacribeiro** [comment]
ci:test:sf

**Review by rebsilva — APPROVED** [review]
LGTM! :cherry_blossom:

**Comment by larissacribeiro** [comment]
ci:test:relevant

**Comment by larissacribeiro** [comment]
ci:test:playwright

**Comment by larissacribeiro** [comment]
ci:test:calendar

**Comment by larissacribeiro** [comment]
ci:test:playwright

**Comment by larissacribeiro** [comment]
ci:test:playwright

**Comment by larissacribeiro** [comment]
ci:test:relevant

**Comment by larissacribeiro** [comment]
ci:test:sf

**Comment by larissacribeiro** [comment]
ci:test:sf

**Comment by larissacribeiro** [comment]
ci:test:relevant

**Comment by larissacribeiro** [comment]
ci:test:playwright

**Comment by larissacribeiro** [comment]
ci:forward

**Pull request closed without merging**
