### PR TITLE
LPD-40798 Can not create entries for the same objects in different sites with the same ERC

### PR DESCRIPTION
**Pull request by abesousa**
Related issue: https://issues.liferay.com/browse/LPD-40798

### CODE REVIEW

**Comment by abesousa** [comment]
ci:test:sf

**Comment by abesousa** [comment]
ci:test:sf

**Comment by marcelabc** [comment]
Just started reviewing :)

**Comment by marcelabc** [comment]
resend: https://github.com/liferay-bpm/liferay-portal/pull/3848

**Pull request closed without merging**
