### PR TITLE
LPD-39417 Published Template version degrades after upgrade

### PR DESCRIPTION
**Pull request by pedro-oliveira446**
[LPD-39417](https://liferay.atlassian.net/browse/LPD-39417)

[LPD-39417]: https://liferay.atlassian.net/browse/LPD-39417?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

### CODE REVIEW

**Comment by pedro-oliveira446** [comment]
ci:test:sf

**Comment by pedro-oliveira446** [comment]
ci:test:relevant

**Comment by pedro-oliveira446** [comment]
ci:test:forms

**Comment by pedro-oliveira446** [comment]
ci:test:upgrade

**Review by linolaoj — APPROVED** [review]

**Comment by pedro-oliveira446** [comment]
Resent https://github.com/brianchandotcom/liferay-portal/pull/155215

**Pull request closed without merging**
