### PR TITLE
LPD-43206 | LPD-44020 Tests - Forms Widgets, Objects Widgets and Collection Display

### PR DESCRIPTION
**Pull request by carolmariaabb**
Task: https://liferay.atlassian.net/browse/LPD-42004

### CODE REVIEW

**Comment by carolmariaabb** [comment]
ci:test:sf

**Comment by carolmariaabb** [comment]
ci:test:sf

**Comment by carolmariaabb** [comment]
ci:test:sf

**Comment by carolmariaabb** [comment]
ci:test:sf

**Review by marcelabc — APPROVED** [review]
LGTM 🎉

**Comment by marcelabc** [comment]
ci:test:relevant

**Comment by carolmariaabb** [comment]
ci:test:sf

**Comment by carolmariaabb** [comment]
ci:forward:force

**Pull request closed without merging**
