### PR TITLE
LPD-40087 - Technical Task | Create Workflow Definition Links endpoint by ERC

### PR DESCRIPTION
**Pull request by JhossephG**
This is the final PR with all the needs to implement the features from story [LPD-36879](https://liferay.atlassian.net/browse/LPD-36879). 

PR of the first task [here](https://github.com/liferay-bpm/liferay-portal/pull/3791)

PR of the second task [here](https://github.com/liferay-bpm/liferay-portal/pull/3780)

[LPD-36879]: https://liferay.atlassian.net/browse/LPD-36879?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

### CODE REVIEW

**Comment by JhossephG** [comment]
ci:test:sf

**Comment by JhossephG** [comment]
ci:test:relevant

**Comment by JhossephG** [comment]
ci:test:workflow

**Comment by linolaoj** [comment]
Hi @JhossephG , as we talked, we will forward the pull request for each task to avoid a single pull request with many commits.

**Comment by linolaoj** [comment]
fist task forwarded here https://github.com/liferay-bpm/liferay-portal/pull/3791

**Comment by JhossephG** [comment]
resent [here](https://github.com/liferay-bpm/liferay-portal/pull/3804)

**Pull request closed without merging**
