### PR TITLE
LPD-38580 Fix tests due the Manage Translations change on Web Content

### PR DESCRIPTION
**Pull request by rebsilva**
Related issue: https://liferay.atlassian.net/browse/LPD-38580

### CODE REVIEW

**Comment by rebsilva** [comment]
ci:test:sf

**Comment by rebsilva** [comment]
i'm going to run the data-engine tests to see if the tests related are passing or not

**Comment by rebsilva** [comment]
ci:test:data-engine

**Comment by rebsilva** [comment]
ci:test:data-engine

**Comment by rebsilva** [comment]
ci:stop

**Comment by igor-franca** [comment]
The changes seem reasonable. Let's wait for the test results to check if everything is in order 😄

**Pull request closed without merging**
